### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by pg731** [dray89/finance_python#3]
Hello and many thanks for the great code and articles on Medium!

I would like to understand the cookie part a bit better.

In your medium [article](https://medium.com/c%C3%B3digo-ecuador/python-web-scraping-stock-market-statistics-on-yahoo-finance-455929c835ed) you didn't give any cookie in the request header, and in my case this created a problem as the request returned yahoo's data privacy consent page.

Using the updated code found in this repository, which includes a cookie, everything works fine.

Could you explain how you've found out how to define the cookie?
Can we always use the cookie value you have hard-coded?

Thanks a lot!

**Comment by dray89** [comment]
Hard coding cookies is not a good idea. This was my very first Python project - hence the hardcoded cookies in these GitHub files. For more information, this article is pretty good: https://levelup.gitconnected.com/if-you-are-web-scraping-dont-do-these-things-2cba2ebe5b29
